version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/running_club
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: running_club
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
